### ISSUE TITLE
What drives need for an `F` effect type in `BinanceConfig`?

### ISSUE THREAD

**Issue by benhutchison** [paoloboni/binance-scala-client#284]
Something I dont understand is why BinanceConfig takes an effect type `F`. It seems to be a pure bag of parameters, so Im unsure why it needs an effect?

Seems to be used only by this `API` type member. What role does that play? Find Usages in IJ didn't report any usage of the field.

https://github.com/paoloboni/binance-scala-client/blob/c2764d820f426bc4ea31681f06b67f06daf51dd2/src/main/scala/io/github/paoloboni/binance/common/BinanceConfig.scala#L33

**Comment by paoloboni** [comment]
Hi @benhutchison. That's a good question, in fact config doesn't need to perform any effectful computation.

The historical reasons behind it can be explained by looking at https://github.com/paoloboni/binance-scala-client/pull/108, changes to support Scala 3. 
Before then `BinanceApi` had a dependency on some type `Config <: BinanceConfig`. A `BinanceApi` factory would require the correct config by using type projections (ie: `API#Config`). 
But since type projections were [dropped](https://docs.scala-lang.org/scala3/reference/dropped-features/type-projection.html) in Scala 3, I had to find another way. At that point I naively introduced this type parameter in `BinanceConfig`.

I reverted some code to the state prior to https://github.com/paoloboni/binance-scala-client/pull/108 and opened https://github.com/paoloboni/binance-scala-client/pull/291. Can you please let me know if that would be reasonable.

**Comment by paoloboni** [comment]
Released in v1.5.0
